apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway-config
  labels:
    {{- include "airlock.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.gateway.config | nindent 4 }}
