apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: airlock-gateway
    instance: {{ .Release.Name }}
    {{- include "airlock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: airlock-gateway
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: airlock-gateway
        instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-token: "auth/token/lookup-self"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: {{ .Values.gateway.terminationGracePeriodSeconds }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          args: ["-config", "/etc/airlock/config.yaml"]
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          {{- if .Values.gateway.env }}
          env:
            {{- toYaml .Values.gateway.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/airlock
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-gateway-config
